DEFAULT_REGION = "ap-southeast-1"

PRODUCTS_TABLE_ENV = "PRODUCTS_TABLE"
CARTS_TABLE_ENV = "CARTS_TABLE"
ORDERS_TABLE_ENV = "ORDERS_TABLE"

DEFAULT_PRODUCTS_TABLE = "harish-tf-products"
DEFAULT_CARTS_TABLE = "harish-tf-carts"
DEFAULT_ORDERS_TABLE = "harish-tf-orders"

CONTENT_TYPE_JSON = "application/json"
ALLOWED_ORIGINS = "*"
ALLOWED_HEADERS = "Content-Type,Authorization,x-correlation-id"
ALLOWED_METHODS = "GET,POST,PUT,DELETE,OPTIONS"
